/*
 * ls339@njit.edu
 * CS435
 */
#include <stdio.h>
#include <stdlib.h>

struct node {
  int row, column, value;
  struct node *row_link, *column_link;
};

struct node* addNode(int row, int column, int value) {

  struct node *head;
  head = malloc(sizeof(struct node));
  head->row = row;
  head->column = column;
  head->value = value;
  head->row_link = NULL;
  head->column_link=NULL;
  return head;
}

void printMatrix(struct node *row[], struct node *column[],int n) {
  int i,j;
  for(i=0;i<n;i++){
    struct node *current = row[i];
    for(j=0;j<n;j++) {
      if(row[i] != NULL) {
	if(current->row == i && current->column == j) {
	  printf(" %d ",current->value);
	  current = current->row_link;
	} else {
	  printf(" 0 ");
	}
      } else {
	printf(" 0 ");
      }
    }
    printf("\n");
  }
}

void insertNode(struct node **row, struct node **column, struct node *nodex) {

  if(nodex->value!=0) {
  /*
   * Insert into row
   */
  struct node* curr;
  if(row[nodex->row]==NULL){
    row[nodex->row] = nodex;
    nodex->row_link = nodex;
  } else {
    curr=row[nodex->row]->row_link;
    while(curr->row_link!=row[nodex->row]) {
      curr=curr->row_link;
    }
    curr->row_link = nodex;
    nodex->row_link = row[nodex->row];
  }
  
  /*
   * Insert into column
   */
  if(column[nodex->column]==NULL) {
    column[nodex->column] = nodex;
    nodex->column_link = nodex;
  } else {
    curr=column[nodex->column]->column_link;
    while(curr->column_link!=column[nodex->column]) {
      curr = curr->column_link;
    }
    curr->column_link = nodex;
    nodex->column_link = column[nodex->column];   
    } 
  }
}

void intializeByInput(int n) {

  struct node *mrow[n];
  struct node *mcolumn[n];
  struct node *matrix[2];  // To-do : use this to return mrow and mcolumn
  struct node *nodex;

  /*
   * NULL out the arrays so we can check for intial empty slots.
   */
  int i;
  for(i=0;i<n;i++) {
    mrow[i] = NULL;
    mcolumn[i] = NULL;
  }

  printf("%d x %d Matrix\n",n,n);
  int c,row,column,value;
  printf("Enter in triples in the following form: (type 'q' to end input)\n");
  printf("Indexing begins at 0\n");
  printf("row column value\n");
  while(1) {
    scanf("%d %d %d", &row, &column, &value);
    c=getchar();
    if(c=='q') {
      break;
    }
    ungetc(c,stdin);
    printf("row = %d , column = %d , value = %d \n", row, column, value);
    nodex = addNode(row,column,value);
    insertNode(mrow,mcolumn,nodex);
  }
  
  // Lets print out our initialized by input matrix.
  printf("Initialized by Input:\n");
  printf("* Matrix A *\n");
  printMatrix(mrow,mcolumn,n);
}

int main(int argc, char **argv) {

  if(argc < 2) {
    printf("Error: You must provide an integer n\n");
    exit(1);
  }

  int i,j;
  struct node *tmp;
  int n = atoi(argv[1]);

  intializeByInput(n);

  /*
   * Test Case 
   */
  struct node *a_row[n];
  struct node *a_column[n];
  for(i=0;i<n;i++) {
    a_row[i] = NULL;
    a_column[i] = NULL;
  }
  insertNode(a_row,a_column,addNode(0,0,8));
  insertNode(a_row,a_column,addNode(0,2,6));
  insertNode(a_row,a_column,addNode(1,1,7));
  insertNode(a_row,a_column,addNode(1,2,5));
  insertNode(a_row,a_column,addNode(2,0,3));
  insertNode(a_row,a_column,addNode(3,3,9));
  printf("\nTest Case Matrix A (autogenerated)\n");
  printMatrix(a_row,a_column,n);

  /*
   * Initialize by formula : Matrix B
   */
  
  struct node *b_row[n];
  struct node *b_column[n];
  for(i=0;i<n;i++){
    for(j=0;j<n;j++){
      if(i==j){
	struct node *nodei = addNode(i,j,i+1);
	b_row[i] = nodei;
	b_column[i] = nodei;
	b_row[i]->row_link = nodei;
	b_column[i]->column_link = nodei;
      }
    }
  }
  printf("\n");
  printf("Initialized by formula:\n");
  printf("\tbij = { i if i==j\n\t\t0 otherwise }\n");
  printf("* Matrix B *\n");
  printMatrix(b_row,b_column,n);
  
  /*
   * Initialize by formula : Matrix C
   */
  
  struct node *c_row[n];
  struct node *c_column[n];
  for(i=0;i<n;i++) {
    c_row[i] = NULL;
    c_column[i] = NULL;
  }
  for(i=0;i<n;i++) {
    for(j=0;j<n;j++) {
      if( (i+1) == ((j+2) % n) ) {
	tmp = addNode(i,j, (-2*(j+1)-1) );
	insertNode(c_row,c_column,tmp);
      }
    }
  }
  printf("\n");
  printf("Initialized by formula:\n");
  printf("\tcij = { -2j-1 if i==j\n\t\t0 otherwise }\n");
  printf("* Matrix C *\n");
  printMatrix(c_row,c_column,n);
  
  /*
   * Initialize by formula : Matrix D
   */
  struct node *d_row[n];
  struct node *d_column[n];
  for(i=0;i<n;i++) {
    d_row[i] = NULL;
    d_column[i] = NULL;
  }
  for(i=0;i<n;i++) {
    for(j=0;j<n;j++) {
      if(((i+1)%2==0) && ((j+1)%2==0)) {
	tmp = addNode(i,j,(i+j+2));
	insertNode(d_row,d_column,tmp);
      } else if (j+1==3) {
	  tmp = addNode(i,j,((i+1)*(-1)));
	insertNode(d_row,d_column,tmp);
      }
    }
  }
  printf("\n");
  printf("Initialized by formula:\n");
  printf("\tcij = { i+j if i==j\n\t\t-i if j == 3\n\t\t0 otherwise }\n");
  printf("* Matrix D *\n");
  printMatrix(d_row,d_column,n);
}
